name: charts-mcp
services:
  sse:
    restart: unless-stopped
    build:
      context: ./sse
      dockerfile: Dockerfile
    ports:
      - "1123:1123"
    volumes:
      - ./sse:/charts-mcp/sse

  streamable:
    restart: unless-stopped
    build:
      context: ./streamable
      dockerfile: Dockerfile
    ports:
      - "1122:1122"
    volumes:
      - ./streamable:/charts-mcp/streamable
